name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checks out the code.
      uses: actions/checkout@v2
    - name: Uploads the artifact. 
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ env.ARTIFACT_NAME }}
        Path: . 
